apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-mongo
  template:
    metadata:
      labels:
        app: application-mongo
    spec:
      containers:
        - name: application-mongo
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: application-mongo-srv
spec:
  selector:
    app: application-mongo
  ports:
    - name: application-mongo # name is not realy important. use any name u like
      protocol: TCP
      port: 27017 # standard mongo port
      targetPort: 27017
