apiVersion: skaffold/v4beta5
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  #googleCloudBuild:
  #  projectId: microservices-dev-392723
  artifacts:
    - image: irick05nazar/auth
      #- image: us.gcr.io/microservices-dev-392723/auth
      context: auth
      sync:
        manual:
          - src: '*.src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
