apiVersion: skaffold/v4beta5
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: irick05nazar/auth
      context: auth
      sync:
        manual:
          - src: '*.src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: irick05nazar/application
      context: application
      sync:
        manual:
          - src: '*.src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: irick05nazar/client
      context: client
      sync:
        manual:
          - src: '*.src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
