apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: irick05nazar/auth
          #env:
          #  - name: JWT_KEY # key set in kubectl
          #    valueFrom:
          #      secretKeyRef:
          #        name: jwt-secret # name of secret from kubectl
          #        key: JWT_KEY # key set in kubectl
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
