name: tests-application

on: 
  pull_request:
    paths:
      - 'application/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd application && npm install && npm run test:ci
